### ISSUE TITLE
PHP fatal after update to 1.21.0

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/registration#35]
```
Fatal error: Declaration of Registration::view($view_mode) must be compatible with Entity::view($view_mode = 'full', $langcode = NULL, $page = NULL) in /Users/jlampton/Sites/_backdrop/events.backdropcms.org/repo/www/modules/contrib/registration/lib/registration.entity.inc on line 269
```

I noticed that there was a new version of `entity_plus` released in August -- `1.x-1.0.13`. I updated to that version in the hopes that it might help (thanks to @quicksketch's recommendation) but no dice.

**Comment by jenlampton** [comment]
I've filed a PR that fixes the problem on my local: https://github.com/backdrop-contrib/registration/pull/36

Not related to entity_plus at all.

**Comment by argiepiano** [comment]
Just a side note. Entity Plus does not define an entity class, so this issue was not produced by the entity_plus update. Rather, this module extended Entity, which is provided as an abstract class in core. Unfortunately as you saw the declaration of the view method suddenly became an override when the view method was added to core. And there was a collision in its declaration.

I tested several modules that rely on Entity Plus and define custom entities, but missed this one. We did some fixes in Rules, Ubercart and Paragraphs. The issues were minimal. The trickiest we found was in Ubercart, but that was because of poor coding (Ubercart is an ancient module that started in D6, and we still have some remnants of a non-entity world there, mixed with some half-baked entity functionality done in D7).

I think people were aware this was a risk - perhaps it's a good idea to have the preview version of minor releases available longer before releasing them?

**Comment by argiepiano** [comment]
Looking back, I actually caught this issue when we were testing the new core's view and buildContent methods! In fact I pinged both @hosef  and @docwilmot . 

I mentioned in [a comment in the core PR](https://github.com/backdrop/backdrop/pull/3848#issuecomment-1002391674) that Registrations used methods that were incompatible with the new core one....

I guess I should have opened an issue here. I was so busy testing Herb's code...

**Comment by jenlampton** [comment]
No need to apologize @argiepiano, you spotted the issue and let us know! Plus, we got it fixed pretty quickly, so no real harm done (I hope!).

**Comment by argiepiano** [comment]
Thanks, @jenlampton !
